{% snapshot T_C1_LIK_CUST_NATION%}
{{
config(
target_database='SDG_DV_TEST',
target_schema='SDG_DV_STG',
unique_key='TS_LOADED_AT',

strategy='timestamp',
updated_at='TS_LOADED_AT',
)
}}

SELECT HASH(C_CUSTKEY || C_NATIONKEY) AS ID_CUST_NATION,
HASH(C_CUSTKEY) AS ID_CUSTOMER,
HASH(C_NATIONKEY) AS ID_NATION,
'SDG_DV_TEST_INGEST.CUSTOMER' AS ST_SOURCE_FROM,
CURRENT_TIMESTAMP AS TS_LOADED_AT
FROM SDG_DV_TEST_INGEST.CUSTOMER
{% endsnapshot %}